name: Run E2E tests

inputs:
  base-url:
    description: "Base URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        PLAYWRIGHT_BASE_URL: ${{ inputs.base-url }}
        VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      shell: bash
