name: Deploy to Vercel

inputs:
  vercel-token:
    description: "Vercel token"
    required: true

  runs:
    using: "composite"
    steps:
      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview  --token=${{ inputs.vercel-token }}

      - name: Build for Vercel
        run: vercel build --token=${{ inputs.vercel-token }}

      - name: Deploy to Vercel
        run: |
          DEPLOY_OUTPUT="$(vercel deploy --token=${{ inputs.vercel-token }})"
          DEPLOY_URL=$(echo "$DEPLOY_OUTPUT" | grep http | tail -n 1)
          echo "DEPLOY_URL=$DEPLOY_URL" >> $GITHUB_ENV
        shell: bash
