name: E2E Tests Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "1 2 3 4 5"

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup

      - name: Run E2E tests
        uses: ./.github/actions/run-e2e-tests
        env:
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        with:
          base-url: ${{ secrets.VERCEL_DEPLOY_URL }}

      - name: If E2E tests failed, send a notification
        if: ${{ failure() }}
        run: node ./.github/actions/run-e2e-tests/failure-webhook.js
        shell: bash
        env:
          FAILURE_WEBHOOK_URL: ${{ secrets.FAILURE_WEBHOOK_URL }}
