name: Deploy to Vercel

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    environment:
      name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup

      - name: Deploy app to Vercel preview
        uses: ./.github/actions/deploy-vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
